<?php

/** @var Payin7_Payments_Block_Form_Payin7 $block */
$block = $this;

/** @var Payin7_Payments_Model_Payin7daysPaymentMethod $method */
$method = $block->getData('method');
$method_code = $method->getCode();
$method_title = $method->getTitle();
$remote_method_code = $method->getRemoteApiPaymentMethodCode();

$checkout_image_url = $block->getData('checkout_image_url');

/** @var Payin7_Payments_Model_Remote_Platform_Config $remote_platform_config */
$remote_platform_config = Mage::getModel('payin7payments/remote_platform_config');
$remote_platform_config->loadData();

$payment_method_config = $remote_platform_config->getPaymentMethodConfig($remote_method_code);

$more_info_content = isset($payment_method_config['more_info_content']) ? trim($payment_method_config['more_info_content']) : null;
$more_info_url = isset($payment_method_config['more_info_url']) ? trim($payment_method_config['more_info_url']) : null;
$more_info_target = isset($payment_method_config['more_info_target']) ? trim($payment_method_config['more_info_target']) : null;

?>
<div class="payin7 checkout-option" data-code="<?php echo $method_code; ?>">
    <img src="<?php echo $checkout_image_url; ?>" class="checkout-img"/>
    <div class="info">
        <span class="method-title"><?php echo $block->escapeHtml($method_title); ?></span>
        <?php if ($more_info_content) { ?>
            <div id="payin7-more-info-<?php echo $remote_method_code; ?>-container" class="more-info-container">
                <?php echo $more_info_content; ?>
            </div>
            <a href="<?php if ($more_info_url) {
                echo $more_info_url;
            } else { ?>#payin7-more-info-<?php echo $remote_method_code; ?>-container<?php } ?>"
            <?php if ($more_info_target) {
                echo ' target="' . $block->escapeHtml($more_info_target) . '" ';
            } ?> class="more-info fancybox"><?php echo $this->__('More Information'); ?></a><?php } else { ?>
            <a href="http://www.payin7.com/faq/magento/checkout/<?php echo $remote_method_code; ?>"
               target="_blank" class="more-info"><?php echo $this->__('More Information'); ?></a>
        <?php } ?>
    </div>
</div>
<script>
    jQuery('.payin7.checkout-option a.more-info.fancybox').fancybox({
        helpers: {
            media: {}
        }
    });
</script>